application: youngerbike
version: 1
runtime: python
api_version: 1
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: helloworld.py
- url: /images
  static_dir: static_dir/images/

